apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
     app: mysql-server
     tier: db
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec:
      containers:
      - name: mysql-server
        image: mysql:5.7
        args:
          - "--datadir=/var/lib/mysql/data"
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim